# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:


    - &OrdererOrg

        Name: OrdereringService


        ID: OrdererMSP


        MSPDir: crypto-config/ordererOrganizations/orh.in/msp

    - &NSP1

        Name: NSP1MSP


        ID: NSP1MSP

        MSPDir: crypto-config/peerOrganizations/nsp1.orh.in/msp

        AnchorPeers:

            - Host: peer0.nsp1.orh.in
              Port: 7051

    - &NSP2

        Name: NSP2MSP


        ID: NSP2MSP

        MSPDir: crypto-config/peerOrganizations/nsp2.orh.in/msp

        AnchorPeers:

            - Host: peer0.nsp1.orh.in
              Port: 7051




Capabilities:

    Global: &ChannelCapabilities

        V1_1: true


    Orderer: &OrdererCapabilities

        V1_1: true


    Application: &ApplicationCapabilities

        V1_2: true

Application: &ApplicationDefaults


    Organizations:


Orderer: &OrdererDefaults


    OrdererType: solo

    Addresses:
        - orderer.orh.in:7050


    BatchTimeout: 2s


    BatchSize:


        MaxMessageCount: 10


        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:

        Brokers:
            - 127.0.0.1:9092

    Organizations:


Profiles:

    TwoOrgsOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *NSP1
                    - *NSP2
    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *NSP1
                - *NSP2
            Capabilities:
                <<: *ApplicationCapabilities
