#Master Organization
OrdererOrgs:
- Name: OrdereringService
  Domain: orh.in
  Specs:
    - Hostname: orderer
#Organization-1
PeerOrgs:
- Name: nsp1
  Domain: nsp1.orh.in
  Template:
     Count: 2
  Users:
     Count: 1
#Organization2 (NSP-1)
- Name: nsp2
  Domain: nsp2.orh.in
  Template:
     Count: 2
  Users:
     Count: 1
